CREATE TABLE ROOM(
  ROOM_ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  ROOM_NUMBER VARCHAR(5) NOT NULL UNIQUE,
  BED_TYPE VARCHAR(25) NOT NULL,
  CHECK_IN_DATE DATE,
  CHECK_OUT_DATE DATE
);

CREATE TABLE GUEST(
  GUEST_ID INT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64) ,
  EMAIL_ADDRESS VARCHAR(64) NOT NULL,
  ADDRESS VARCHAR(64) NOT NULL,
  COUNTRY VARCHAR(32) NOT NULL,
  STATE VARCHAR(12) NOT NULL,
  PHONE_NUMBER VARCHAR(24) NOT NULL
);

CREATE TABLE RESERVATION(
  RESERVATION_ID INT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID BIGINT NOT NULL,
  GUEST_ID BIGINT NOT NULL,
  RES_DATE DATE
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);
CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
